# Updated Model Configuration for MMCB
# Both models successfully downloaded and verified

# Mistral model (working)
- name: "Mistral-7B"
  type: "mistral"
  path: "mistralai/Mistral-7B-Instruct-v0.2"
  device: "mps"  # Optimized for M3 Pro
  cache_dir: "~/models/huggingface"
  description: "Mistral AI's 7B instruction-tuned model - Downloaded and verified"

# Llama model (working)  
- name: "Llama-3-8B"
  type: "llama"
  path: "meta-llama/Meta-Llama-3-8B-Instruct"
  device: "mps"  # Optimized for M3 Pro
  cache_dir: "~/models/huggingface"
  description: "Meta's Llama 3 8B instruction-tuned model - Downloaded and verified"